### ISSUE TITLE
jakarta.xml.bind.PropertyException when running application with Jakarta EE9 

### ISSUE THREAD

**Issue by tam512** [OpenLiberty/open-liberty#18442]
- Run transformer tool to convert an application binary ear file to Jakarta EE9
```
$ java -jar org.eclipse.transformer.cli-0.3.0-SNAPSHOT.jar SocialSphereEAR-ee7.ear SocialSphereEAR-ee9.ear -td jakarta-direct.properties -tf file.properties -td jakarta-restfulWS.properties
```
- when run the SocialSphereEAR-ee9.ear app in Liberty 21.0.0.9, I see the following exception in Liberty messages.log

```
[9/3/21, 13:31:22:144 CDT] 00000030 binding.jaxb.3.2.jakarta:1.0.56.cl210920210824-2341(id=160)] I Class jakarta.xml.bind.JAXBElement does not have a default constructor which JAXB requires.
[9/3/21, 13:31:22:147 CDT] 00000030 .cxf.rt.wsdl.3.2.jakarta:1.0.56.cl210920210824-2341(id=166)] I Creating Service {http://advertisement.sphere.social.ibm.com/}AdvertisementImplService from WSDL: http://localhost:81/SocialSphereWebService/AdvertisementImplService?wsdl
[9/3/21, 13:31:22:154 CDT] 00000030 binding.jaxb.3.2.jakarta:1.0.56.cl210920210824-2341(id=160)] I Class jakarta.xml.bind.JAXBElement does not have a default constructor which JAXB requires.
[9/3/21, 13:31:22:178 CDT] 00000030 binding.jaxb.3.2.jakarta:1.0.56.cl210920210824-2341(id=160)] I PropertyException setting Marshaller properties
jakarta.xml.bind.PropertyException: name: org.glassfish.jaxb.runtime.ObjectFactory value: jakarta.xml.bind.JAXBElementFactory@4d74c45e
	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.setProperty(AbstractUnmarshallerImpl.java:327)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.setProperty(UnmarshallerImpl.java:474)
	at org.apache.cxf.jaxb.io.DataReaderImpl.createUnmarshaller(DataReaderImpl.java:124)
	at org.apache.cxf.jaxb.io.DataReaderImpl.read(DataReaderImpl.java:168)
	at org.apache.cxf.wsdl.interceptors.DocLiteralInInterceptor.handleMessage(DocLiteralInInterceptor.java:109)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:831)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1749)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1623)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1419)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:687)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:140)
	at com.sun.proxy.$Proxy147.getAdsByIDJPA(Unknown Source)
	at com.ibm.social.sphere.advertisement.AdvertisementFactory.getAds(AdvertisementFactory.java:16)
	at com.ibm._jsp._webservices._jspService(_webservices.java:107)
	at com.ibm.ws.jsp.runtime.HttpJspBase.service(HttpJspBase.java:100)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
	at com.ibm.wsspi.webcontainer.servlet.GenericServletWrapper.handleRequest(GenericServletWrapper.java:118)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.handleRequest(AbstractJSPExtensionServletWrapper.java:211)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:183)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:94)
	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1011)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
	at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:85)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
```
- full log file: [messages.log.zip](https://github.com/OpenLiberty/open-liberty/files/7108055/messages.log.zip)

**Comment by tam512** [comment]
Hi @neuwerk is there a plan on when this problem will be fixed?  
I can not close my Jakarta EE9 testcase if this is not fixed and Brian Hanczaryk can't sign off SVT for this feature.

**Comment by jhanders34** [comment]
Can you try with a newer version of Liberty?  I believe this may have been resolved in the last few weeks with a change that Andrew Rouse did.

**Comment by tam512** [comment]
@jhanders34 I just tried with newer daily build `21.0.0.11 (wlp-1.0.58.cl211120211005-1900)` and I still see the same error
```
[10/6/21, 12:07:56:702 CDT] 00000043 binding.jaxb.3.2.jakarta:1.0.58.cl211120211005-1900(id=163)] I PropertyException setting Marshaller properties
jakarta.xml.bind.PropertyException: name: org.glassfish.jaxb.runtime.ObjectFactory value: jakarta.xml.bind.JAXBElementFactory@b1b002ef
	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.setProperty(AbstractUnmarshallerImpl.java:327)
```

**Comment by tam512** [comment]
Jared sent me a patch `com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2.jakarta_1.0.58.jar` and I don't see the error anymore, but I see these messages. 
```
[10/6/21, 14:02:51:670 CDT] 00000047 .cxf.rt.wsdl.3.2.jakarta:1.0.58.cl211120211005-1900(id=170)] I Creating Service {http://advertisement.sphere.social.ibm.com/}AdvertisementImplService from WSDL: http://localhost:82/SocialSphereWebService/AdvertisementImplService?wsdl
[10/6/21, 14:02:51:672 CDT] 00000047 rt.databinding.jaxb.3.2.jakarta:1.0.58.202110061319(id=163)] I Class jakarta.xml.bind.JAXBElement does not have a default constructor which JAXB requires.
[10/6/21, 14:02:51:674 CDT] 00000047 .cxf.rt.wsdl.3.2.jakarta:1.0.58.cl211120211005-1900(id=170)] I Creating Service {http://advertisement.sphere.social.ibm.com/}AdvertisementImplService from WSDL: http://localhost:82/SocialSphereWebService/AdvertisementImplService?wsdl
[10/6/21, 14:02:51:677 CDT] 00000047 rt.databinding.jaxb.3.2.jakarta:1.0.58.202110061319(id=163)] I Class jakarta.xml.bind.JAXBElement does not have a default constructor which JAXB requires.
```

**Comment by tam512** [comment]
Old log for the app in JEE7 shows:
```
[9/1/21, 17:50:40:712 CDT] 00000044 org.apache.cxf.endpoint.ServerImpl                           I Setting the server's publish address to be /AdvertisementImplService
[9/1/21, 17:50:40:712 CDT] 00000044 org.apache.cxf.management.jmx.InstrumentationManagerImpl     I registering MBean org.apache.cxf:bus.id=SocialSphereWebService-1.0-Server-Bus,type=Bus.Service.Endpoint,service="{http://advertisement.sphere.social.ibm.com/}AdvertisementImplService",port="AdvertisementImplPort",instance.id=2061918901: org.apache.cxf.endpoint.ManagedEndpoint@fc968577
```

**Comment by jhanders34** [comment]
The patch I provided will require #18907 in order to resolve it.

**Comment by tam512** [comment]
Verified that the problem is fixed in the latest Liberty build.  Close this issue.
