### ISSUE TITLE
Jakarta Data: Prefix "DATA" added to table name / name of the table specified by @Table(name= "table-name") is ignored

### ISSUE THREAD

**Issue by ltlBeBoy** [OpenLiberty/open-liberty#28580]
**Describe the bug**  
I was running a demo with OpenLiberty version 24.0.0.6-beta and Jakarta Data. During startup I noticed in the log that the prefix `DATA` was added to the expected table name. So I tried to specify the table name by adding `@Table(name = "address")` to the entity. But the expected name of the table is still `DATAAddress`. So I changed the name of the table in the database to the expected value, and everything worked (except for the `DROP` commands which are not permitted by database).

**Steps to Reproduce**  
Create a simple project with the specified entity, repository and resource.

**Expected behavior**  
No `DATA` prefix is added to the expected table name. Also `@Table(name = "address")` should not be ignored.

**Diagnostic information:** 
 - Log:
   [messages.log](https://github.com/OpenLiberty/open-liberty/files/15482119/messages.log)
 - OpenLiberty Version: 24.0.0.6-beta
 - Affected feature(s): data-1.0
 - Java Version:
   java version "21" 2023-09-19 LTS
  Java(TM) SE Runtime Environment (build 21+35-LTS-2513)
  Java HotSpot(TM) 64-Bit Server VM (build 21+35-LTS-2513, mixed mode, sharing)
- server.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">
    <featureManager>
        <feature>data-1.0</feature>
        <feature>jsonb-3.0</feature>
        <feature>persistence-3.1</feature>
        <feature>restfulWS-3.1</feature>
    </featureManager>

    <httpEndpoint id="defaultHttpEndpoint"
                  host="127.0.0.1"
                  httpPort="${default.http.port}"
                  httpsPort="${default.https.port}" />

    <applicationManager autoExpand="true" />

    <webApplication contextRoot="/mk-shop-rest"
                    location="mk-shop-rest.war" />

    <library id="mariaDbJDBCLib">
        <fileset dir="${server.config.dir}/lib/global/jdbc"
                 includes="mariadb-java-client.jar" />
    </library>

    <dataSource id="mkShopDataSource"
                jndiName="jdbc/mk-shop"
                type="javax.sql.XADataSource">
        <!-- see https://openliberty.io/docs/latest/relational-database-connections-JDBC.html#unknown -->
        <jdbcDriver libraryRef="mariaDbJDBCLib"
                    javax.sql.XADataSource="org.mariadb.jdbc.MariaDbDataSource" />
        <properties URL="jdbc:mariadb://localhost:3306/mk-shop"
                    user="user"
                    password="password" />
    </dataSource>
</server>
```

**Additional context**  
_**Entity:**_
```
import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Entity
@Table(name = "address")
@Data
public class Address {
    @Id
    @GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "num")
    private long num;
}

```

_**Repository:**_
```
import jakarta.data.repository.BasicRepository;
import jakarta.data.repository.Repository;

@Repository(dataStore = "jdbc/mk-shop")
public interface Addresses extends BasicRepository<Address, Long> {

}
```

_**Resource:**_
```
import java.util.List;

import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/addresses")
public class AddressResource {

    @Inject
    private Addresses addresses;

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public List<Address> getAllAddresses() {
        List<Address> addressList = addresses.findAll()
                .toList();

        return addressList;
    }
}
```

**Comment by njr-11** [comment]
Thanks for reporting this.  I switched the label from `release bug` to `bug` given that it's in beta rather than released function.  We have been more focused in the beta on trying to meet the specification requirements and less so on the configuration aspects, but configuration is definitely an area we want to get right before release, so thanks again for pointing this out!

**Comment by njr-11** [comment]
The feature needed for this, as well as a bug fix, have been implemented in development builds and it should be working in the `24008-beta` of Open Liberty when that becomes available.

**Comment by ltlBeBoy** [comment]
Great, I will test it when it becomes available. Many thanks!

**Comment by ltlBeBoy** [comment]
OK, I tried with _Open Liberty 24.0.0.7-beta_, but at me it's still the same. Should I provide a little reproducer, or are you not interested currently?

**Comment by ltlBeBoy** [comment]
Ah, sorry, you was writing `24008-beta`. Then I have to wait for the next beta version.

**Comment by tjwatson** [comment]
I'm running on the latest release branch with a similar configuration.  I don't see `DATA` being prefixed.  Instead, I see `WLP` get prefixed.

I have an InstantOn test that shows this in my PR #28979.  There I had to use `wlpuser` as the table name when initializing the database with test data (https://github.com/OpenLiberty/open-liberty/pull/28979/files#diff-195a464afe35f4a658260133f8a0a73131b95f684f09bab31063b671d1a658efR65-R80)

**Comment by njr-11** [comment]
@tjwatson please use a different git issue because you have a different scenario.  Unlike the user who opened this issue, you are not specifying any `dataStore=` on your `@Repository` to ask for a specific data source/database configuration to be used.  That means you are accepting the default, which currently includes a prefix.  We can separately consider if the behavior you are getting is what we want.  But the issue reported by the user who opened this issue (where they specify a data source without a prefix but get one anyway) was fixed separately.

**Comment by tjwatson** [comment]
> @tjwatson please use a different git issue

I opened #28995

**Comment by ltlBeBoy** [comment]
I can confirm that the issues I mentioned previously are no longer present with _Open Liberty 24.0.0.8-beta_. The `DATA` prefix is ​​no longer prepended and `@Table` is now processed as expected.

Many thanks for the great work.
