### ISSUE TITLE
Open liberty 23.x/24.x/25.x, CDI4, WELD-001414: Bean name is ambiguous

### ISSUE THREAD

**Issue by mrinalkumari06** [OpenLiberty/open-liberty#31525]
I have 2 WARs in the EAR which has some common dependency of web-fragments e.g I have test-sample.jar which has multiple CDI beans. And WAR1 and WAR2 both has this library in the WEB-INF/lib

In Open liberty 23.x/24.x/25.x, in server deployment getting below error:

**[ERROR ] CWWKZ0002E: An exception occurred while starting the application XXX-server. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-001414: Bean name is ambiguous.**

Earlier was using CDI2 so it was working fine. Now migrated to CDI4 and started seeing this issue. WAR1 is not in our control, that is coming from some other application through dependency.

How can we solve this problem?

Tried to move the common jar files to some shared location , but since WAR1 is not in our control we cannot do that.

Is there any open liberty server configuration or any library conflicts which is causing this issue.

This the only error I am getting.

**Comment by benjamin-confino** [comment]
Hello.

We attempted to recreate this locally but our test application worked without error. Are you able to send your the ear file and server.xml file? If you can we can verify it locally.

If not please can you add the following to your server.xml. `<logging traceSpecification="**=info:JCDI=all:com.ibm.ws.cdi*=all:com.ibm.ws.weld*=all:org.jboss.*=all:Injection=all"/>` and then after recreating the error sending us all your traces, the server.xml, and if possible just the list of files within the ear and its internal jar files.

Regards
Benjamin

**Comment by mrinalkumari06** [comment]
Please find attached server.xml and trace log in the zip file.

My EAR file structure is like as below: 

**test-server.ear**:
         -lib
		 -META-INF
		 -**WebApplication1.war**
			- META-INF
			- WEB-INF
				- App1.jar
				- App2.jar
				- App3.jar
				- omnifaces-4.4.1.jar
				- primefaces-14.0.12-jakarta.jar
				- primefaces-extensions-14.0.12-jakarta
		 -**WebApplication2.war**
			- META-INF
			- WEB-INF
		 		- App1.jar
				- App2.jar
				- App3.jar
				- omnifaces-4.4.1.jar
				- primefaces-14.0.12-jakarta.jar
				- primefaces-extensions-14.0.12-jakarta

**Comment by benjamin-confino** [comment]
I'm sorry to have annoying news but your trace.log file cut off all but the last 12 megabytes of trace meaning all the useful stuff is missing. 

Are there more trace files like trace_25.05.13_15.01.21.0.log and if so please can you send them? If not please can you update your trace statement to this: 

       ` <logging traceSpecification="**=info:JCDI=all:com.ibm.ws.cdi*=all:com.ibm.ws.weld*=all:org.jboss.*=all:Injection=all:TELEMETRY=all" maxFileSize="200" maxFiles="10" traceFileName="logs/trace.log"/>`

You should see a line like 

`[5/13/25, 14:59:40:194 BST] 00000001 id=00000000 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0001I: The server Telemetry10TCKServer has been launched.`

Near the top of the trace.

**Comment by mrinalkumari06** [comment]
Attaching trace.log and server log.
Also attached trace_25.05.14_12.35.07.0.log, but don't see "The server Telemetry10TCKServer has been launched." related log

**Comment by benjamin-confino** [comment]
Are you certain there are only two files? With the elements ` maxFileSize="200" maxFiles="10"` I suggested in my previous message, and the way your trace files start in the middle of application startup, there should be more.

**Comment by mrinalkumari06** [comment]
Yes, There are only two trace files generated.

**Comment by benjamin-confino** [comment]
That is weird. Unfortunately there's not much I can do without the logs covering the relevant part of startup or a recreate app. Are you able to open a support ticket? If so the second line support are experienced with getting hold of good logs.

**Comment by mrinalkumari06** [comment]
I enabled telemetry feature and also used openliberty 24.0.012, Now  I can see some of telemetry logs.
But still don't see "The server Telemetry10TCKServer has been launched." in logs

Attaching the trace logs.

**The server installed the following features**: [appAuthentication-3.0, appAuthorization-2.1, appClientSupport-2.0, appSecurity-5.0, batch-2.1, beanValidation-3.0, cdi-4.0, concurrent-3.0, connectors-2.1, distributedMap-1.0, enterpriseBeans-4.0, enterpriseBeansHome-4.0, enterpriseBeansLite-4.0, enterpriseBeansPersistentTimer-4.0, enterpriseBeansRemote-4.0, expressionLanguage-5.0, faces-4.0, jakartaee-10.0, jdbc-4.2, jndi-1.0, jsonb-3.0, jsonp-2.1, mail-2.1, managedBeans-2.0, mdb-4.0, messaging-3.1, messagingClient-3.0, messagingSecurity-3.0, messagingServer-3.0, monitor-1.0, mpConfig-3.1, mpTelemetry-2.0, pages-3.1, persistence-3.1, persistenceContainer-3.1, restfulWS-3.1, restfulWSClient-3.1, servlet-6.0, ssl-1.0, transportSecurity-1.0, webProfile-10.0, websocket-2.1, xmlBinding-4.0, xmlWS-4.0].

**Comment by benjamin-confino** [comment]
Hello again. 

These are the logs I have been looking for. I see `CWWKE0001I: The server TXMServer01 has been launched` at the start. And more importantly lots and lots of interesting information.

Lets start with the obvious. CustomerSearchBean is in two jars: 

```
trace_25.05.15_15.51.07.0.log:[5/15/25, 15:50:09:986 IST] 0000002f id=00000000 com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl           3 scan [ BDA for test-server#server.war#WEB_INF_LIB#WEB-INF/lib/core-ocm-wf.jar(WEB_INF_LIB) ] AFTER SCAN. Bean classes: { 

trace_25.05.15_15.51.07.0.log:[5/15/25, 15:50:28:004 IST] 0000002f id=00000000 com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl           3 scan [ BDA for test-server#vm-webmarketing.war#WEB_INF_LIB#WEB-INF/lib/core-ocm-wf.jar(WEB_INF_LIB) ] AFTER SCAN. Bean classes: {
```
(I'll leave out the very long lists of bean classes)

Secondly if you search for the string `will be visible to` there is no BDA that can see both of these. Which is as it should be. 

But that's the obvious and expected stuff, now we get to the interesting part!

```
trace.log:[5/15/25, 15:51:34:801 IST] 00000064 id=00000000 org.jboss.weld.bean.AbstractBean                              internalInitialize WELD-000016: Using scope interface jakarta.faces.view.ViewScoped for Managed Bean [class com.wincor.adminconsole.usermanagement.customer.CustomerSearchBean] with qualifiers [@Default @Any @Named]
```

CustomerSearchBean is ViewScoped. That is interesting because ViewScoped is not part of the CDI spec, and must be added to CDI via a CDI extension. Which is something that may have changed between CDI 1.2 and 4.0. But when I looked for extension in the log: 

```
trace_25.05.15_15.51.07.0.log:[5/15/25, 15:51:07:028 IST] 0000002f id=00000000 org.jboss.weld.bootstrap.ExtensionBeanDeployer               1 deployBean WELD-000168: Extension bean deployed: Extension [class org.omnifaces.cdi.viewscope.ViewScopeExtension] with qualifiers [@Default]; wsjar:file:/c:/Users/test.user/openliberty-24.0.0.12/wlp/usr/servers/TXMServer01/apps/test-server.ear/vm-webmarketing.war/WEB-INF/lib/omnifaces-4.6.2.jar!/META-INF/services/jakarta.enterprise.inject.spi.Extension@1[org.omnifaces.cdi.viewscope.ViewScopeExtension@7fa3c682]
```

So you have two different frameworks attempting to handle ViewScope, you have the one built into liberty, `The server installed the following features: faces-4.0`. and omnifaces. This is the sort of thing that can cause the error you've seen if both framework registers a CustomerSearchBean with CDI. 

I can't say for sure if this is the issue, I'm not experienced with ViewScoped in general, but my suggestion is to update your server.xml, remove features you don't need including faces-4.0. Let me know if that resolves the issue.

**Comment by mrinalkumari06** [comment]
Thanks for your response.

We are facing issue with SessionScoped beans also. Bean Ambiguity error comes for random beans of any scope ViewScoped or SessionScoped

faces-4.0 feature comes with jakartaee-10.0 feature. I do not include jakartaee-10.0 feature then getting error related to jakarta packages. So not sure how to exclude faces-4.0

I have these 2 entries in server.xml:
   <featureManager>
        <feature>jakartaee-10.0</feature> 
	<feature>mpTelemetry-2.0</feature>
    </featureManager>

And in server console I can see below features included:

The server installed the following features: [appAuthentication-3.0, appAuthorization-2.1, appClientSupport-2.0, appSecurity-5.0, batch-2.1, beanValidation-3.0, cdi-4.0, concurrent-3.0, connectors-2.1, distributedMap-1.0, enterpriseBeans-4.0, enterpriseBeansHome-4.0, enterpriseBeansLite-4.0, enterpriseBeansPersistentTimer-4.0, enterpriseBeansRemote-4.0, expressionLanguage-5.0, faces-4.0, jakartaee-10.0, jdbc-4.2, jndi-1.0, jsonb-3.0, jsonp-2.1, mail-2.1, managedBeans-2.0, mdb-4.0, messaging-3.1, messagingClient-3.0, messagingSecurity-3.0, messagingServer-3.0, monitor-1.0, mpConfig-3.1, mpTelemetry-2.0, pages-3.1, persistence-3.1, persistenceContainer-3.1, restfulWS-3.1, restfulWSClient-3.1, servlet-6.0, ssl-1.0, transportSecurity-1.0, webProfile-10.0, websocket-2.1, xmlBinding-4.0, xmlWS-4.0]

**Comment by benjamin-confino** [comment]
> faces-4.0 feature comes with jakartaee-10.0 feature. I do not include jakartaee-10.0 feature then getting error related to jakarta packages. So not sure how to exclude faces-4.0

What you can do is replace <feature>jakartaee-10.0</feature> with <feature>appAuthentication-3.0</feature>, <feature>appAuthorization-2.1</feature>. The whole list of features you see above, then start removing the ones your application does not require including removing faces-4.0

Of course I cannot say which ones you do or do not need since I'm not familiar with your application.

**Comment by mrinalkumari06** [comment]
Tried including the whole list of features , and then removed them one by one which are not in use. 
Without faces.4.0 feature , getting server startup error:
"The exception message was: com.ibm.ws.container.service.state.StateChangeException: java.lang.NoClassDefFoundError: jakarta/faces/model/DataModel"

From the application perspective, faces 4.0 is required.

**Comment by volosied** [comment]
The error in the logs is: 
```
org.jboss.weld.exceptions.DeploymentException: WELD-001414: Bean name is ambiguous. Name CustomerSearchBean resolves to beans: 
[Managed Bean [class com.wincor.adminconsole.usermanagement.customer.CustomerSearchBean] with qualifiers [@Default @Any @Named], 
 Managed Bean [class com.wincor.adminconsole.usermanagement.customer.CustomerSearchBean] with qualifiers [@Default @Any @Named]]
```

I looked into the dependencies to ensure there's no other `CustomerSearchBean` bean. 
- omnifaces-4.4.1.jar
- primefaces-14.0.12-jakarta.jar
- primefaces-extensions-14.0.12-jakarta


My guess is that there's a duplicate class somewhere in the app code.  However, I'm also wondering if it has something do with the ear structure. Let me look more into it.

**Comment by volosied** [comment]
For this error: 
org.jboss.weld.exceptions.DeploymentException: 
WELD-001414: Bean name is ambiguous. Name guestPreferences resolves to beans: [
Managed Bean [class org.primefaces.ultima.view.GuestPreferences] with qualifiers [@Default @Named @Any],
Managed Bean [class org.primefaces.ultima.view.GuestPreferences] with qualifiers [@Default @Named @Any]]
```

Though, what change since CustomerSearchBean was reported in the other logs? 

What if you place the  files: 

- omnifaces-4.4.1.jar
- primefaces-14.0.12-jakarta.jar
- primefaces-extensions-14.0.12-jakarta.jar 

into the root level lib folder?  (instead of in each war?)

**Comment by volosied** [comment]
@mrinalkumari06 

I _cannot_ reproduce the error when I try. Is there anyway you could you using my sample skeleton app project? 

[multi-ear-project.zip](https://github.com/user-attachments/files/20251381/multi-ear-project.zip) 

Thanks!

**Comment by benjamin-confino** [comment]
I had another look, and found that there's a third potential source of ViewScoped beans:  myfaces

```
trace.log:[5/15/25, 15:51:35:336 IST] 0000002f id=00000000 org.jboss.weld.bootstrap.events.AfterBeanDiscoveryImpl       1 addContext WELD-000156: AfterBeanDiscovery.addContext() called by org.apache.myfaces.cdi.view.ViewScopeExtension@5c3b8a5c for org.apache.myfaces.cdi.view.ViewScopeContext@29548bcb
trace.log:[5/15/25, 15:51:35:346 IST] 0000002f id=00000000 org.jboss.weld.bootstrap.events.AfterBeanDiscoveryImpl       1 addContext WELD-000156: AfterBeanDiscovery.addContext() called by org.omnifaces.cdi.viewscope.ViewScopeExtension@5fa4373f for org.omnifaces.cdi.viewscope.ViewScopeContext@37fdb03b
trace.log:[5/15/25, 15:51:35:358 IST] 0000002f id=00000000 org.jboss.weld.bootstrap.events.AfterBeanDiscoveryImpl       1 addContext WELD-000156: AfterBeanDiscovery.addContext() called by org.omnifaces.cdi.viewscope.ViewScopeExtension@7fa3c682 for org.omnifaces.cdi.viewscope.ViewScopeContext@30030cbd
```

But nothing immediately jumped to mind as an explenation for how you could be getting two copies of session scoped beans. Is it any particular SessionScoped bean or some specific ones? If the latter, what are their names?

**Comment by volosied** [comment]
Could you also get a classloading trace for us? - ` <logging traceSpecification="*=info:com.ibm.ws.classloading*=all"/> `

**Comment by mrinalkumari06** [comment]
> <logging traceSpecification="*=info:com.ibm.ws.classloading*=all"/>

After adding above trace here is the trace files:

**Comment by mrinalkumari06** [comment]
> I had another look, and found that there's a third potential source of ViewScoped beans: myfaces
> 
> ```
> trace.log:[5/15/25, 15:51:35:336 IST] 0000002f id=00000000 org.jboss.weld.bootstrap.events.AfterBeanDiscoveryImpl       1 addContext WELD-000156: AfterBeanDiscovery.addContext() called by org.apache.myfaces.cdi.view.ViewScopeExtension@5c3b8a5c for org.apache.myfaces.cdi.view.ViewScopeContext@29548bcb
> trace.log:[5/15/25, 15:51:35:346 IST] 0000002f id=00000000 org.jboss.weld.bootstrap.events.AfterBeanDiscoveryImpl       1 addContext WELD-000156: AfterBeanDiscovery.addContext() called by org.omnifaces.cdi.viewscope.ViewScopeExtension@5fa4373f for org.omnifaces.cdi.viewscope.ViewScopeContext@37fdb03b
> trace.log:[5/15/25, 15:51:35:358 IST] 0000002f id=00000000 org.jboss.weld.bootstrap.events.AfterBeanDiscoveryImpl       1 addContext WELD-000156: AfterBeanDiscovery.addContext() called by org.omnifaces.cdi.viewscope.ViewScopeExtension@7fa3c682 for org.omnifaces.cdi.viewscope.ViewScopeContext@30030cbd
> ```
> 
> But nothing immediately jumped to mind as an explenation for how you could be getting two copies of session scoped beans. Is it any particular SessionScoped bean or some specific ones? If the latter, what are their names?

The reason why there is two copies of session scoped beans the common jar dependencies in two WAR files

**Comment by mrinalkumari06** [comment]
> For this error: org.jboss.weld.exceptions.DeploymentException: WELD-001414: Bean name is ambiguous. Name guestPreferences resolves to beans: [ Managed Bean [class org.primefaces.ultima.view.GuestPreferences] with qualifiers [[@default](https://github.com/default) [@nAmed](https://github.com/nAmed) @Any], Managed Bean [class org.primefaces.ultima.view.GuestPreferences] with qualifiers [[@default](https://github.com/default) [@nAmed](https://github.com/nAmed) @Any]]
> 
> ```
> 
> Though, what change since CustomerSearchBean was reported in the other logs? 
> 
> What if you place the  files: 
> 
> - omnifaces-4.4.1.jar
> - primefaces-14.0.12-jakarta.jar
> - primefaces-extensions-14.0.12-jakarta.jar 
> 
> into the root level lib folder?  (instead of in each war?)
> ```

omnifaces needs to be placed inside the WAR/lib folder, this is the restriction for ominfaces

https://github.com/omnifaces/omnifaces/wiki/Known-Issues-(CDI)

**Comment by benjamin-confino** [comment]
Sorry, I got pulled away. I had a look at the new traces but it has the same issue as the original set. Can you re-do what you did with trace_25.05.15.zip, and make sure you see: CWWKE0001I: The server TXMServer01 has been launched

**Comment by patildeval** [comment]
@benjamin-confino This looks similar to https://www.ibm.com/support/pages/apar/PI46218

**Comment by patildeval** [comment]
> [@mrinalkumari06](https://github.com/mrinalkumari06)
> 
> I _cannot_ reproduce the error when I try. Is there anyway you could you using my sample skeleton app project?
> 
> [multi-ear-project.zip](https://github.com/user-attachments/files/20251381/multi-ear-project.zip)
> 
> Thanks!

@volosied I tried sample project provided by you, and noticed following exception 

`[ERROR   ] CWWKZ0106E: Could not start web application ear-1.0-SNAPSHOT.
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application ear-1.0-SNAPSHOT. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-001414: Bean name is ambiguous. Name WebAppBean resolves to beans: [Managed Bean [class com.test.WebAppBean] with qualifiers [@Default @Named @Any], Managed Bean [class com.test.WebAppBean] with qualifiers [@Default @Named @Any]]`

**server.xml**
`<?xml version="1.0" encoding="UTF-8"?>
<server description="ear-1.0-SNAPSHOT">
	
	<featureManager>
		<feature>jakartaee-10.0</feature>
	</featureManager>
	<keyStore id="defaultKeyStore" location="${java.home}/lib/security/cacerts" password="changeit" type="JKS"/>
	<quickStartSecurity userName="admin" userPassword="admin123"/>
	<enterpriseApplication id="ear-1.0-SNAPSHOT" location="ear-1.0-SNAPSHOT.ear" name="ear-1.0-SNAPSHOT"/>
</server>
`

**Comment by patildeval** [comment]
@volosied  on each run different bean is there in the exception

**Run-2**
`[ERROR   ] CWWKZ0002E: An exception occurred while starting the application ear-1.0-SNAPSHOT. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-001414: Bean name is ambiguous. Name sharedBean resolves to beans: [Managed Bean [class com.example.SharedBean] with qualifiers [@Default @Any @Named], Managed Bean [class com.example.SharedBean] with qualifiers [@Default @Any @Named]]`

**Run-3**
`[ERROR   ] CWWKZ0002E: An exception occurred while starting the application ear-1.0-SNAPSHOT. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-001414: Bean name is ambiguous. Name now resolves to beans: [Producer Method [TemporalDate] with qualifiers [@Default @Any @Named] declared as [[BackedAnnotatedMethod] @Produces @Named @RequestScoped public org.omnifaces.cdi.config.DateProducer.getNow()], Producer Method [TemporalDate] with qualifiers [@Default @Any @Named] declared as [[BackedAnnotatedMethod] @Produces @Named @RequestScoped public org.omnifaces.cdi.config.DateProducer.getNow()]]`

**Comment by mrinalkumari06** [comment]
> Sorry, I got pulled away. I had a look at the new traces but it has the same issue as the original set. Can you re-do what you did with trace_25.05.15.zip, and make sure you see: CWWKE0001I: The server TXMServer01 has been launched

Hi @benjamin-confino 
Here are the today's logs:

[trace_25.05.28.zip](https://github.com/user-attachments/files/20483136/trace_25.05.28.zip)

**Comment by benjamin-confino** [comment]
@mrinalkumari06 The good news is I've figured out exactly what is going on. Its a bug in liberty, so thank you for bringing that to our attention. The bad news is that its going to be tricky to fix. The other good news is that the workaround is simple. 

If a Liberty feature creates a BDA including all application classes, then it can generate this error. And since you have `<feature>jakartaee-10.0</feature>` you have some of those. If you cut your server.xml down to just the minimum needed features that should resolve this.

The feature that threw the error was `appSecurity`, but there may be others in that long list that are exposed to this bug

**Comment by patildeval** [comment]
> @mrinalkumari06 The good news is I've figured out exactly what is going on. Its a bug in liberty, so thank you for bringing that to our attention. The bad news is that its going to be tricky to fix. The other good news is that the workaround is simple. 
> 
> If a Liberty feature creates a BDA including all application classes, then it can generate this error. And since you have `<feature>jakartaee-10.0</feature>` you have some of those. If you cut your server.xml down to just the minimum needed features that should resolve this.
> 
> The feature that threw the error was `appSecurity`, but there may be others in that long list that are exposed to this bug

@benjamin-confino, I figured this out earlier in the day when I tried adding features to a simple project shared by @volosied. However, I couldn’t pinpoint the issue in the Liberty code base. Multiple features, including jakartaee-10.0 and webprofile, could be causing this problem.

**Comment by benjamin-confino** [comment]
@patildeval To pinpoint the issue in the liberty codebase you need to look for classes that implement the interface `CDIExtensionMetadataInternal`, and override `applicationBeansVisible()` to return true. There's an older deprecated way of setting the same flag, but if you're on jakartaee-10.0 I do not think that would be relevant. 

`jakartaee` and `webprofile` are both meta features. They do not enable any code directly but they do enable other features which enable code. 

In the server.xml posted above the only feature listed is `<feature>jakartaee-10.0</feature>`. But when you start the server you get the following mesage: 

[AUDIT   ] CWWKF0012I: The server installed the following features: [appAuthentication-3.0, appAuthorization-2.1, appClientSupport-2.0, appSecurity-5.0, batch-2.1, beanValidation-3.0, cdi-4.0, concurrent-3.0, connectors-2.1, distributedMap-1.0, enterpriseBeans-4.0, enterpriseBeansHome-4.0, enterpriseBeansLite-4.0, enterpriseBeansPersistentTimer-4.0, enterpriseBeansRemote-4.0, expressionLanguage-5.0, faces-4.0, jakartaee-10.0, jdbc-4.2, jndi-1.0, jsonb-3.0, jsonp-2.1, mail-2.1, managedBeans-2.0, mdb-4.0, messaging-3.1, messagingClient-3.0, messagingSecurity-3.0, messagingServer-3.0, pages-3.1, persistence-3.1, persistenceContainer-3.1, restfulWS-3.1, restfulWSClient-3.1, servlet-6.0, ssl-1.0, transportSecurity-1.0, webProfile-10.0, websocket-2.1, xmlBinding-4.0, xmlWS-4.0].


Those are all the features enabled by `jakartaee-10.0`, so what you can do is remove `<feature>jakartaee-10.0</feature>` and in its place add only the features you actually need in its place.

**Comment by patildeval** [comment]
Hi @benjamin-confino 

Could you kindly inform me which Liberty feature is required to enable `com.ibm.ws.threadContext.ComponentMetaDataAccessorImpl.getComponentMetaData() ` functionality?

currently dealing with 

> Caused by: java.lang.NullPointerException: Cannot invoke "com.ibm.ws.runtime.metadata.ComponentMetaData.getModuleMetaData()" because the return value of "com.ibm.ws.threadContext.ComponentMetaDataAccessorImpl.getComponentMetaData()" is null
        at com.ibm.ws.beanvalidation.v20.cdi.internal.LibertyValidatorProxy.delegate(LibertyValidatorProxy.java:39)
        at com.ibm.ws.beanvalidation.v20.cdi.internal.LibertyValidatorProxy.validate(LibertyValidatorProxy.java:65)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
        at org.jboss.weld.generated.proxies.validation.Validator$2141568514$Proxy$_$$_WeldClientProxy.validate(Unknown Source)

Enabled Features:

> 
            <feature>beanValidation-3.0</feature>
		<feature>cdi-4.0</feature>
		<feature>connectors-2.1</feature>
		<feature>expressionLanguage-5.0</feature>
		<feature>faces-4.0</feature>
		<feature>jsonp-2.1</feature>
		<feature>mail-2.1</feature>
		<feature>restfulWS-3.1</feature>
		<feature>restfulWSClient-3.1</feature>
		<feature>servlet-6.0</feature>
		<feature>transportSecurity-1.0</feature>
		<feature>websocket-2.1</feature>
		<feature>xmlBinding-4.0</feature>
            <feature>persistence-3.1</feature>
            <feature>persistenceContainer-3.1</feature>
            <feature>monitor-1.0</feature>
		<feature>xmlWS-4.0</feature>

Thanks

**Comment by benjamin-confino** [comment]
Try adding `concurrent-3.0`, @patildeval 

That looks to me like TheadContext hasn't been propagated which is usually handled by `concurrent`. I'm a bit surprised to see that problem on a thread started inside weld, but lets try the obvious fix first.

**Comment by patildeval** [comment]
@benjamin-confino 
concurrent-3.0 , again results in 

> The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-001414: Bean name is ambiguous.

**Comment by benjamin-confino** [comment]
@patildeval At least we are back to an error message I understand, can you send me the full [AUDIT ] CWWKF0012I: The server installed the following features: message from your messages.log please?

**Comment by patildeval** [comment]
@benjamin-confino 

> 
[5/29/25, 19:14:12:926 IST] 00000029 com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0012I: The server installed the following features: [beanValidation-3.0, cdi-4.0, concurrent-3.0, connectors-2.1, expressionLanguage-5.0, faces-4.0, jdbc-4.2, jndi-1.0, jsonp-2.1, mail-2.1, monitor-1.0, persistence-3.1, persistenceContainer-3.1, restfulWS-3.1, restfulWSClient-3.1, servlet-6.0, ssl-1.0, transportSecurity-1.0, websocket-2.1, xmlBinding-4.0, xmlWS-4.0].

**Comment by benjamin-confino** [comment]
I have bad news. If you enable `concurrent-3.0` and `cdi-4.0` togeather, that will enable the integration code for those two features, and that includes io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtensionMetadata.java

I think the only way forward from here is for you to raise a support ticket, link them to this issue where I would say that it has to go to the L3 desk and I try to create a patch to resolve this.

**Comment by patildeval** [comment]
Hi @benjamin-confino 
The application started successfully with the following features installed:

>  [6/3/25, 10:57:47:648 IST] 00000029 com.ibm.ws.kernel.feature.internal.FeatureManager A CWWKF0012I: The server installed the following features:
[batch-2.1, beanValidation-3.0, cdi-4.0, connectors-2.1, distributedMap-1.0, enterpriseBeans-4.0, enterpriseBeansHome-4.0, enterpriseBeansLite-4.0, enterpriseBeansPersistentTimer-4.0, enterpriseBeansRemote-4.0, expressionLanguage-5.0, faces-4.0, jdbc-4.2, jndi-1.0, jsonb-3.0, jsonp-2.1, mail-2.1, managedBeans-2.0, mdb-4.0, messaging-3.1, messagingClient-3.0, messagingSecurity-3.0, messagingServer-3.0, monitor-1.0, pages-3.1, persistence-3.1, persistenceContainer-3.1, restfulWS-3.1, restfulWSClient-3.1, servlet-6.0, ssl-1.0, transportSecurity-1.0, websocket-2.1, xmlBinding-4.0, xmlWS-4.0].

However, a new error related to the class loader has occurred. It seems that multiple class loaders are loading the same class, resulting in a ClassCastException.

>[6/3/25, 12:00:57:577 IST] 00000290 org.omnifaces.filter.FacesExceptionFilter                    E 944f5732-10a4-4ec7-b807-b6b5f0278213][0:0:0:0:0:0:0:1] FacesExceptionFilter: An exception occurred during processing servlet request. Error page '/errorHandler' will be shown. java.lang.ClassCastException: class org.primefaces.context.PrimeRequestContext cannot be cast to class org.primefaces.context.PrimeRequestContext (org.primefaces.context.PrimeRequestContext is in unnamed module of loader **_com.ibm.ws.classloading.internal.AppClassLoader @4648bdbd_**; org.primefaces.context.PrimeRequestContext is in unnamed module of loader **_com.ibm.ws.classloading.internal.AppClassLoader @34b60945_**) at org.primefaces.context.PrimeRequestContext.getCurrentInstance(PrimeRequestContext.java:83) at org.primefaces.application.resource.PrimeResource.<init>(PrimeResource.java:43) at org.primefaces.application.resource.PrimeResourceHandler.wrapResource(PrimeResourceHandler.java:97) at org.primefaces.application.resource.PrimeResourceHandler.createResource(PrimeResourceHandler.java:63) at jakarta.faces.application.ResourceHandlerWrapper.createResource(ResourceHandlerWrapper.java:54) at jakarta.faces.application.ResourceHandlerWrapper.createResource(ResourceHandlerWrapper.java:54) at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:79) at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:79) at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:79) at org.apache.myfaces.el.resolver.ResourceResolver.getValue(ResourceResolver.java:141) at jakarta.el.CompositeELResolver.getValue(CompositeELResolver.java:62) at org.apache.el.parser.AstValue.getValue(AstValue.java:169) at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190) at org.apache.myfaces.resource.ValueExpressionFilterInputStream.read(ValueExpressionFilterInputStream.java:133) at java.base/java.io.InputStream.read(InputStream.java:293) at java.base/java.io.InputStream.read(InputStream.java:218) at org.apache.myfaces.application.ResourceHandlerImpl.pipeBytes(ResourceHandlerImpl.java:647) at org.apache.myfaces.application.ResourceHandlerImpl.handleResourceRequest(ResourceHandlerImpl.java:590) at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72) at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72) at org.primefaces.application.resource.PrimeResourceHandler.handleResourceRequest(PrimeResourceHandler.java:78) at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72) at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72) at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72) at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72) at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72) at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:215) at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1266) at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:754) at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:451) at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:197) at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:100)


Any insights or solutions would be greatly appreciated!

**Comment by benjamin-confino** [comment]
@patildeval I have good news, I've just merged a PR that will resolve this issue. 

If you wait until then you can grab a nightly build here: https://openliberty.io/start/#development_builds

**Comment by patildeval** [comment]
@benjamin-confino 

Thanks for the update! We really appreciate the fix. However, we're still encountering the following issue: it seems like multiple class loaders are loading the same class, leading to a ClassCastException. Additionally, we're noticing some unexpected behavior with resource handling and ServletException errors related to buffer size.
Here’s a snippet of the errors we're seeing:

**ClassCastException**
> [6/10/25, 18:45:35:465 IST] 00000057 com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'org.primefaces.context.PrimeRequestContext.getCurrentInstance:83'
java.lang.ClassCastException: class org.primefaces.context.PrimeRequestContext cannot be cast to class org.primefaces.context.PrimeRequestContext (**org.primefaces.context.PrimeRequestContext is in unnamed module of loader com.ibm.ws.classloading.internal.AppClassLoader @1ec9ec7d; org.primefaces.context.PrimeRequestContext is in unnamed module of loader com.ibm.ws.classloading.internal.AppClassLoader @4be7dbc1)**
	at org.primefaces.context.PrimeRequestContext.getCurrentInstance(PrimeRequestContext.java:83)
	at org.primefaces.application.resource.PrimeResource.<init>(PrimeResource.java:43)
	at org.primefaces.application.resource.PrimeResourceHandler.wrapResource(PrimeResourceHandler.java:97)
	at org.primefaces.application.resource.PrimeResourceHandler.createResource(PrimeResourceHandler.java:63)
	at jakarta.faces.application.ResourceHandlerWrapper.createResource(ResourceHandlerWrapper.java:54)
	at org.primefaces.extensions.application.PrimeFacesExtensionsResourceHandler.createResource(PrimeFacesExtensionsResourceHandler.java:46)
	at jakarta.faces.application.ResourceHandlerWrapper.createResource(ResourceHandlerWrapper.java:54)
	at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:79)
	at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:79)
	at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:79)
	at org.apache.myfaces.el.resolver.ResourceResolver.getValue(ResourceResolver.java:141)
	at jakarta.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at org.apache.myfaces.resource.ValueExpressionFilterInputStream.read(ValueExpressionFilterInputStream.java:133)
	at java.base/java.io.InputStream.read(InputStream.java:293)
	at java.base/java.io.InputStream.read(InputStream.java:218)
	at org.apache.myfaces.application.ResourceHandlerImpl.pipeBytes(ResourceHandlerImpl.java:647)
	at org.apache.myfaces.application.ResourceHandlerImpl.handleResourceRequest(ResourceHandlerImpl.java:590)
	at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
	at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
	at org.primefaces.application.resource.PrimeResourceHandler.handleResourceRequest(PrimeResourceHandler.java:78)
	at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)



Would really appreciate any insights or suggestions on how to resolve this! Thanks in advance.

**Comment by patildeval** [comment]
@benjamin-confino 

just following up to see if there’s been any update on this issue. Have you had a chance to look into the ClassCastException .

based on the behavior, it seems quite similar to the ambiguous beans issue, possibly related to having the same JAR present in multiple WARs within an EAR, leading to multiple classloaders loading the same class differently. Let me know if this aligns with your analysis or if there's anything I can help clarify further.

Thanks so much for your time and support!

**Comment by benjamin-confino** [comment]
Hello, I'm afraid the ClassCastException is outside my area of expertise. I did ask someone to have a look, and I'll send them a reminder.

**Comment by volosied** [comment]
Hi, I'll try to help out on this ClassCastException.  

1) I don't recall if we asked you to try placing the primefaces jars under EAR/lib?   If not, please give that a try. 

2) If the above doesn't work, use your original setup, but with parentLast. Then add this to the server.xml: 
```
<enterpriseApplication location="myApp.ear" name="MyApp">
    <classloader delegation="parentLast"/>
</enterpriseApplication>
```
3)  Another option, it to create a shared library for common dependencies.  Something like:

````
<library id="primefacesLib">
    <fileset dir="lib" includes="*.jar"/>
</library>

<application location="myapp.ear">
    <classloader commonLibraryRef="primefacesLib"/>
</application>
```


You might need to move the app to a different location / specify the path in order to get it to be picked up. 

 I'll keep investigating and may request some traces. 

Thanks for your patience.

**Comment by volosied** [comment]
Or are you somehow exposing the `PrimeRequestContext` class from WAR 1 to WAR 2 somehow?  Is there any resource sharing?

**Comment by volosied** [comment]
😄  I'm able to reproduce the error -- I'll debug it to see how to best address it.  Ultimately, I think one of the 3 options above will likely be it.  But perhaps there may be another option. Thanks!

**Comment by volosied** [comment]
I added debug, and I see the issue (also evident from the stack trace).

But I don't see a fix without refactoring the app. The root cause of the ClassCastException is duplicate loading of PrimeRequestContext by two different WAR classloaders in the EAR.

`org.primefaces.context.PrimeRequestContext` loads the class with the first app during a request. Then when processing a request with the second app, the saved PrimeRequestContext (on the facesContext attributes) throws an exception since the loaded runtime PrimeRequestContext from the first app was somehow used instead.  Different classes as seen by the JVM, so it throws that exception. 

```
[6/25/25, 14:47:10:372 EDT] 0000005a SystemOut                                                    O >>> [PrimeFaces DEBUG] Raw object: org.primefaces.context.PrimeRequestContext@23375906
[6/25/25, 14:47:10:372 EDT] 0000005a SystemOut                                                    O >>> [PrimeFaces DEBUG] Object class: class org.primefaces.context.PrimeRequestContext
[6/25/25, 14:47:10:372 EDT] 0000005a SystemOut                                                    O >>> [PrimeFaces DEBUG] Object classloader: com.ibm.ws.classloading.internal.AppClassLoader@44943db4
[6/25/25, 14:47:10:372 EDT] 0000005a SystemOut                                                    O >>> [PrimeFaces DEBUG] Expected class: class org.primefaces.context.PrimeRequestContext
[6/25/25, 14:47:10:372 EDT] 0000005a SystemOut                                                    O >>> [PrimeFaces DEBUG] Expected classloader: com.ibm.ws.classloading.internal.AppClassLoader@589f4675
[6/25/25, 14:47:10:372 EDT] 0000005a SystemOut                                                    O >>> [PrimeFaces DEBUG] Class equals: false
```

Same thing via `-verbose:class`:
```
app1:
[27.768s][info][class,load  ] org.primefaces.context.PrimeRequestContext source: file: ...wlp/usr/servers/defaultServer/apps/expanded/ear-1.0-SNAPSHOT.ear/com.example-webapp1-1.0-SNAPSHOT.war/WEB-INF/lib/primefaces-14.0.12-jakarta.jar
...
app2:
[30.489s][info][class,load  ] org.primefaces.context.PrimeRequestContext source: file: ...wlp/usr/servers/defaultServer/apps/expanded/ear-1.0-SNAPSHOT.ear/com.example-webapp2-1.0-SNAPSHOT.war/WEB-INF/lib/primefaces-14.0.12-jakarta.jar
```

My guess: perhaps class cache? 

Either way I recommend one of the 3 options above.

**Comment by jhanders34** [comment]
> My guess: perhaps class cache?

The problem would not be class cache related.  The class cache ends up caching classes based off of the URL of the classes' locations.  In this case there are two different URL because the same class is in two different WAR modules in the application.  Each WAR module gets its own ClassLoader which loads each class independently.  If you try to cast an instance of a Class from one ClassLoader to a class from a different ClassLoader, you will get a ClassCastException since they aren't the same class because they are from different ClassLoaders even if the classes are identical to each other as to their contents.  This ClassLoader behavior is defined by Java and is not specific to Liberty.

As suggested already if multiple WARs need to depend on a common set of classes, it is important to have the those classes in a shared ClassLoader that both WARs can access that is application scoped instead of module scoped.  This is necessary if a module may need to view the classes of the other module.  Additionally it reduces the size of your application since you don't have duplicates of jars in multiple modules.  That is where the suggestions above are important.  I am not sure if the #2 suggestion will work because fundamentally it is the same application so will still have the same problem with two ClassLoaders loading two instances of the class.

**Comment by patildeval** [comment]
@volosied / @jhanders34 / @benjamin-confino 

Thanks, appreciate your efforts!

Just a few points regarding the issue:
- These issues are observed only on Open Liberty; everything works fine with JBoss 8.
- The problems started after our migration to Jakarta. Prior to that, everything was functioning as expected. Below are the Liberty features used in both setups:

`Without Jakarta`
```
CWWKF0012I: The server installed the following features:
[appSecurity-2.0, beanValidation-1.1, cdi-1.2, concurrent-1.0, distributedMap-1.0, ejb-3.2, ejbHome-3.2, ejbLite-3.2, ejbPersistentTimer-3.2, ejbRemote-3.2, el-3.0, javaMail-1.5, jaxb-2.2, jaxrs-2.0, jaxrsClient-2.0, jaxws-2.2, jca-1.7, jdbc-4.1, jndi-1.0, jpa-2.1, jpaContainer-2.1, jsf-2.2, json-1.0, jsonp-1.0, jsp-2.3, mdb-3.2, monitor-1.0, servlet-3.1, ssl-1.0, transportSecurity-1.0, websocket-1.1]
```
`With Jakarta`
```
CWWKF0012I: The server installed the following features:
[appAuthentication-3.0, appAuthorization-2.1, appClientSupport-2.0, appSecurity-5.0, batch-2.1, beanValidation-3.0, cdi-4.0, concurrent-3.0, connectors-2.1, distributedMap-1.0, enterpriseBeans-4.0, enterpriseBeansHome-4.0, enterpriseBeansLite-4.0, enterpriseBeansPersistentTimer-4.0, enterpriseBeansRemote-4.0, expressionLanguage-5.0, faces-4.0, jakartaee-10.0, jdbc-4.2, jndi-1.0, jsonb-3.0, jsonp-2.1, mail-2.1, managedBeans-2.0, mdb-4.0, messaging-3.1, messagingClient-3.0, messagingSecurity-3.0, messagingServer-3.0, monitor-1.0, pages-3.1, persistence-3.1, persistenceContainer-3.1, restfulWS-3.1, restfulWSClient-3.1, servlet-6.0, ssl-1.0, transportSecurity-1.0, webProfile-10.0, websocket-2.1, xmlBinding-4.0, xmlWS-4.0]
```
- Previously, we encountered an ambiguous bean issue caused by the concurrent feature when using the Jakarta umbrella feature. That was resolved by @benjamin-confino under issue #31734  . However, we have since begun noticing issues related to multiple class loaders. From the behavior, it seems reminiscent of the ambiguous beans issue—possibly stemming from the same JAR being present in multiple WARs within an EAR, leading to classloader inconsistencies.
- Regarding moving dependencies to a shared library: it's not feasible to move PrimeFaces or OmniFaces to the shared lib because they are web fragments and must reside in WEB-INF/lib.

**Comment by patildeval** [comment]
Hi @volosied 
Hope you are doing good.
Have there been any updates on this issue? Any progress or insights would be greatly appreciated!

**Comment by volosied** [comment]
Hi, I apologize.  I didn't realize you commented and I haven't looked at this. 

I will need to reach out to some class loading experts to see if they have any suggestions as this problem with the dual libraries is outside my expertise. 

That said, if you can't move your dependencies to a shared library, then I recommending testing with option 2 -- parentLast classloading : 

```
<enterpriseApplication location="myApp.ear" name="MyApp">
  <classloader delegation="parentLast"/>
</enterpriseApplication>

```

That should allow you to use your app as is, without any changes.  It worked for my sample app, at least.

**Comment by volosied** [comment]
I've confirmed parentLast seems to be the best option if you can't use a shared library as referenced by `enterpriseApplication` or grouped under EAR/lib. 

> Q: So when each WAR gets its own classloader within the EAR, the same classloader is reused to load the same class— hence no ClassCastException. Is that accurate?
> 
> A: Yes.  Each WAR class loader will load these classes from its local class path when parentLast delegation is enabled, assuming the classes are assembled/provided in each WAR.
