### ISSUE TITLE
NullPointerException in TokenLoginModule.setUpTemporaryUserSubjectForJsonWebToken()

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#3545]
I have a test case that's manually building a JWT with the following claims:

```JSON
{"token_type":"Bearer","iss":"https://9.53.49.176:8020/jwt/builder_defaults","exp":1526309527,"iat":1526302327}
```

Note the `"upn"` and `"sub"` claims are missing. I add that JWT as a cookie into a request to a protected resource and encounter a few expected FFDCs, but also an NPE:

```
------Start of DE processing------ = [5/14/18 7:52:08:756 CDT]
Exception = java.lang.NullPointerException
Source = com.ibm.ws.security.authentication.jaas.modules.TokenLoginModule
probeid = 106
Stack Dump = java.lang.NullPointerException
    at com.ibm.ws.security.authentication.utility.SubjectHelper$1.run(SubjectHelper.java:105)
    at com.ibm.ws.security.authentication.utility.SubjectHelper$1.run(SubjectHelper.java:99)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.ibm.ws.security.authentication.utility.SubjectHelper.getHashtableFromSubject(SubjectHelper.java:99)
    at com.ibm.ws.security.authentication.jaas.modules.TokenLoginModule.setUpTemporaryUserSubjectForJsonWebToken(TokenLoginModule.java:168)
    at com.ibm.ws.security.authentication.jaas.modules.TokenLoginModule.login(TokenLoginModule.java:86)
    at com.ibm.ws.kernel.boot.security.LoginModuleProxy.login(LoginModuleProxy.java:51)
    [ ... ]
    at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.doLoginContext(JAASServiceImpl.java:343)
    at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.performLogin(JAASServiceImpl.java:329)
    at com.ibm.ws.security.authentication.internal.jaas.JAASServiceImpl.performLogin(JAASServiceImpl.java:314)
    at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.performJAASLogin(AuthenticationServiceImpl.java:479)
    at com.ibm.ws.security.authentication.internal.AuthenticationServiceImpl.authenticate(AuthenticationServiceImpl.java:205)
    at com.ibm.ws.webcontainer.security.internal.SSOAuthenticator.authenticateWithJwt(SSOAuthenticator.java:243)

```

**Comment by utle** [comment]
Fixed in PR #3442

**Comment by ayoho** [comment]
Re-opening because I'm still seeing an NPE in the same test flow, although it's in a slightly different spot:

```
------Start of DE processing------ = [5/21/18 14:15:41:238 CDT]
Exception = java.lang.NullPointerException
Source = com.ibm.ws.security.authentication.jaas.modules.TokenLoginModule
probeid = 110
Stack Dump = java.lang.NullPointerException
	at com.ibm.ws.security.authentication.jaas.modules.TokenLoginModule.setUpTemporaryUserSubjectForJsonWebToken(TokenLoginModule.java:170)
	at com.ibm.ws.security.authentication.jaas.modules.TokenLoginModule.login(TokenLoginModule.java:90)
	at com.ibm.ws.kernel.boot.security.LoginModuleProxy.login(LoginModuleProxy.java:51)
```

That line (170) corresponds to here:

```Java
private void setUpTemporaryUserSubjectForJsonWebToken(String jwtToken) throws Exception {
    Subject jwtPartialSubject = new Subject();
    jwtPartialSubject = JwtSSOTokenHelper.handleJwtSSOToken(jwtToken);
    Set<Principal> jwtPrincipals = jwtPartialSubject.getPrincipals(); // <--- This line
    temporarySubject = new Subject();
    temporarySubject.getPrincipals().addAll(jwtPrincipals);
```
